### ISSUE TITLE
Kernel keeps dying

### ISSUE THREAD

**Issue by ghost** [suvarchal/IJython#3]
``` 
File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/x/github/IJython/jython_kernel.py", line 55
    abort_msg = {'status': 'abort',
                                  ^
TabError: inconsistent use of tabs and spaces in indentation
[I 21:00:06.283 NotebookApp] KernelRestarter: restarting kernel (1/5)
```

**Comment by suvarchal** [comment]
repo is awaiting a major update with many changes to jupyter meanwhile, in about a week i will try to update it.

**Comment by ivvv** [comment]
I managed to fix those tabs and spaces problem and the kernel compiles OK and I can load it in a notebook. However, trying the example
`import java` OK
`print dir(java)` Nothing appears on output

And I see the following exception in kernel:

[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/xxx/miniconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/xxx/miniconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/xxx/Tmp/IJython/jython_kernel.py", line 58, in do_execute
    output = self.jyrepl(code, timeout=None)
  File "/Users/xxx/Tmp/IJython/jython_kernel.py", line 158, in jyrepl
    if len(self._child.before.splitlines())>1:    out+='\n'.join(self._child.before.splitlines()[1:])+'\n'
TypeError: sequence item 0: expected str instance, bytes found

Is this exception related with the fact that I used python3.6 to install the kernel?

Do I need to use python2.7?

**Comment by adutchengineer** [comment]
This is still an issue.
